// <auto-generated />
namespace RoomManage.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adduserTypecolumntousertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adduserTypecolumntousertable));
        
        string IMigrationMetadata.Id
        {
            get { return "201908232040207_add-userType-column-to-usertable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
