// <auto-generated />
namespace RoomManage.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addrelationshipbetweenuserandcommment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addrelationshipbetweenuserandcommment));
        
        string IMigrationMetadata.Id
        {
            get { return "201908232105451_add-relationship-between-user-and-commment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
