//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomManage.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoomManage.Resources.AccountController", typeof(AccountController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated Account Successfully.
        /// </summary>
        public static string ActivateAccountSuccessMessage {
            get {
                return ResourceManager.GetString("ActivateAccountSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string ActiveUserAccount {
            get {
                return ResourceManager.GetString("ActiveUserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to activate this accont.
        /// </summary>
        public static string ActiveUserAccountConfrimMessage {
            get {
                return ResourceManager.GetString("ActiveUserAccountConfrimMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddAdmin.
        /// </summary>
        public static string AddAdmin {
            get {
                return ResourceManager.GetString("AddAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirm New Password.
        /// </summary>
        public static string confirmNewPassword {
            get {
                return ResourceManager.GetString("confirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirm Password.
        /// </summary>
        public static string confirmPassword {
            get {
                return ResourceManager.GetString("confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirm Password is Required.
        /// </summary>
        public static string confirmPasswordRequiredMessage {
            get {
                return ResourceManager.GetString("confirmPasswordRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateNewAccount.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Role.
        /// </summary>
        public static string CreateNewRole {
            get {
                return ResourceManager.GetString("CreateNewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeActivate.
        /// </summary>
        public static string DeActiveUserAccount {
            get {
                return ResourceManager.GetString("DeActiveUserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are you sure  deActivate this account.
        /// </summary>
        public static string DeActiveUserAccountConfrimMessage {
            get {
                return ResourceManager.GetString("DeActiveUserAccountConfrimMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are you sure to delete this comment or sugguest.
        /// </summary>
        public static string DeleteCommentConfrimMessage {
            get {
                return ResourceManager.GetString("DeleteCommentConfrimMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete comment or suggest successfully.
        /// </summary>
        public static string DeleteCommentSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteCommentSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Data Successfully.
        /// </summary>
        public static string EditSuccessfully {
            get {
                return ResourceManager.GetString("EditSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email isRequired.
        /// </summary>
        public static string EmailRequiredMessage {
            get {
                return ResourceManager.GetString("EmailRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullLocation.
        /// </summary>
        public static string FullLocation {
            get {
                return ResourceManager.GetString("FullLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullLocation is Required.
        /// </summary>
        public static string FullLocationRequiredMessage {
            get {
                return ResourceManager.GetString("FullLocationRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin And Users.
        /// </summary>
        public static string getAdminAndUsers {
            get {
                return ResourceManager.GetString("getAdminAndUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getAdmins.
        /// </summary>
        public static string getAdmins {
            get {
                return ResourceManager.GetString("getAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get Users.
        /// </summary>
        public static string getUsers {
            get {
                return ResourceManager.GetString("getUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new Password.
        /// </summary>
        public static string newPassword {
            get {
                return ResourceManager.GetString("newPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewPassword IsNot Corricted.
        /// </summary>
        public static string NewPasswordIsNotCorrict {
            get {
                return ResourceManager.GetString("NewPasswordIsNotCorrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to newPassword is Required.
        /// </summary>
        public static string newPasswordRequiredMessage {
            get {
                return ResourceManager.GetString("newPasswordRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oldPassword.
        /// </summary>
        public static string oldPassword {
            get {
                return ResourceManager.GetString("oldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oldPassword is Required.
        /// </summary>
        public static string oldPasswordRequiredMessage {
            get {
                return ResourceManager.GetString("oldPasswordRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Not Math.
        /// </summary>
        public static string PasswordNotMathErrorMessage {
            get {
                return ResourceManager.GetString("PasswordNotMathErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is Required.
        /// </summary>
        public static string PasswordRequiredMessage {
            get {
                return ResourceManager.GetString("PasswordRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumber.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumber is Required.
        /// </summary>
        public static string PhoneNumberRequiredMessage {
            get {
                return ResourceManager.GetString("PhoneNumberRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemmeberMe?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Information.
        /// </summary>
        public static string RoleInfo {
            get {
                return ResourceManager.GetString("RoleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage User Roles.
        /// </summary>
        public static string RoleManage {
            get {
                return ResourceManager.GetString("RoleManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Role Name.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeActivated Account Successfully.
        /// </summary>
        public static string UnActivateAccountSuccessMessage {
            get {
                return ResourceManager.GetString("UnActivateAccountSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User List.
        /// </summary>
        public static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage User.
        /// </summary>
        public static string UserManage {
            get {
                return ResourceManager.GetString("UserManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName is Required.
        /// </summary>
        public static string UserNameRequiredMessage {
            get {
                return ResourceManager.GetString("UserNameRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserType.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wellcom.
        /// </summary>
        public static string UserWellcom {
            get {
                return ResourceManager.GetString("UserWellcom", resourceCulture);
            }
        }
    }
}
