//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomManage.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BarrennessController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BarrennessController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoomManage.Resources.BarrennessController", typeof(BarrennessController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add comment or over to help us to solve problem in  this wapsite.
        /// </summary>
        public static string AddCommentWellcomMessage {
            get {
                return ResourceManager.GetString("AddCommentWellcomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Applied Barrennes to buy or to leased.
        /// </summary>
        public static string AppliedBarrennesWellComMessage {
            get {
                return ResourceManager.GetString("AppliedBarrennesWellComMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applier Message.
        /// </summary>
        public static string ApplierMessage {
            get {
                return ResourceManager.GetString("ApplierMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Date.
        /// </summary>
        public static string ApplyDate {
            get {
                return ResourceManager.GetString("ApplyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your apply for tnis barrennes later.
        /// </summary>
        public static string ApplyErrorMessage {
            get {
                return ResourceManager.GetString("ApplyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply For Barrennes.
        /// </summary>
        public static string ApplyForBarrennes {
            get {
                return ResourceManager.GetString("ApplyForBarrennes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply For This barrennes to buy or leased this barrennes.
        /// </summary>
        public static string ApplyMessage {
            get {
                return ResourceManager.GetString("ApplyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to applier message filed is required.
        /// </summary>
        public static string ApplyMessageRequired {
            get {
                return ResourceManager.GetString("ApplyMessageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply suucessfully you can continuity to barrennnes publisher by using phoneNumber or chating in this wepsite.
        /// </summary>
        public static string ApplySuccessMessage {
            get {
                return ResourceManager.GetString("ApplySuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to barreness Description.
        /// </summary>
        public static string barrenessDescription {
            get {
                return ResourceManager.GetString("barrenessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Appliied Barrennes .
        /// </summary>
        public static string BarrennesApplied {
            get {
                return ResourceManager.GetString("BarrennesApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all user whose applied for this barrennes.
        /// </summary>
        public static string BarrennesApplier {
            get {
                return ResourceManager.GetString("BarrennesApplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Barrennes Categories.
        /// </summary>
        public static string BarrennesCategoryManage {
            get {
                return ResourceManager.GetString("BarrennesCategoryManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BarrennesfullLocation.
        /// </summary>
        public static string BarrennesfullLocation {
            get {
                return ResourceManager.GetString("BarrennesfullLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrennes Info.
        /// </summary>
        public static string BarrennesInfo {
            get {
                return ResourceManager.GetString("BarrennesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrennes Number.
        /// </summary>
        public static string BarrennesNumber {
            get {
                return ResourceManager.GetString("BarrennesNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrennes Of This Category.
        /// </summary>
        public static string BarrennesOfCategory {
            get {
                return ResourceManager.GetString("BarrennesOfCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrennes State.
        /// </summary>
        public static string BarrennesState {
            get {
                return ResourceManager.GetString("BarrennesState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BarrennesStatus.
        /// </summary>
        public static string BarrennesStatus {
            get {
                return ResourceManager.GetString("BarrennesStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chating Room.
        /// </summary>
        public static string ChatingRoom {
            get {
                return ResourceManager.GetString("ChatingRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment And Suggest.
        /// </summary>
        public static string CommentAndsuggest {
            get {
                return ResourceManager.GetString("CommentAndsuggest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date that you want to search in it.
        /// </summary>
        public static string CommentSearchDate {
            get {
                return ResourceManager.GetString("CommentSearchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this barrennes.
        /// </summary>
        public static string confirmDeleteBarrennes {
            get {
                return ResourceManager.GetString("confirmDeleteBarrennes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this barrennes.
        /// </summary>
        public static string DeleteBarrennes {
            get {
                return ResourceManager.GetString("DeleteBarrennes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditBarrennesInfo.
        /// </summary>
        public static string EditBarrennesInfo {
            get {
                return ResourceManager.GetString("EditBarrennesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lease Price.
        /// </summary>
        public static string leasePrice {
            get {
                return ResourceManager.GetString("leasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go to my barrennes.
        /// </summary>
        public static string MyBarrennes {
            get {
                return ResourceManager.GetString("MyBarrennes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to payment Method.
        /// </summary>
        public static string paymentMethod {
            get {
                return ResourceManager.GetString("paymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Barrennes.
        /// </summary>
        public static string PublishBarrennes {
            get {
                return ResourceManager.GetString("PublishBarrennes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to publish Date.
        /// </summary>
        public static string publishDate {
            get {
                return ResourceManager.GetString("publishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Published Barrennes.
        /// </summary>
        public static string PublishedBarrennes {
            get {
                return ResourceManager.GetString("PublishedBarrennes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to publisher.
        /// </summary>
        public static string publisher_id {
            get {
                return ResourceManager.GetString("publisher_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reciver.
        /// </summary>
        public static string reciver {
            get {
                return ResourceManager.GetString("reciver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Barrennes.
        /// </summary>
        public static string SearchBarrennes {
            get {
                return ResourceManager.GetString("SearchBarrennes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search barrennes by state of barrennes and category of barrennes.
        /// </summary>
        public static string SearchMessage {
            get {
                return ResourceManager.GetString("SearchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Barrennes Category.
        /// </summary>
        public static string SelectBarrennes {
            get {
                return ResourceManager.GetString("SelectBarrennes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select State.
        /// </summary>
        public static string SelectState {
            get {
                return ResourceManager.GetString("SelectState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendComment.
        /// </summary>
        public static string SendComment {
            get {
                return ResourceManager.GetString("SendComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send Date.
        /// </summary>
        public static string sendDate {
            get {
                return ResourceManager.GetString("sendDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sender.
        /// </summary>
        public static string sender {
            get {
                return ResourceManager.GetString("sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Comment And suggests.
        /// </summary>
        public static string UserCommentAndsuggest {
            get {
                return ResourceManager.GetString("UserCommentAndsuggest", resourceCulture);
            }
        }
    }
}
